backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: src/assets
public_folder: /assets
collections:
  - name: "friends"
    label: "Friends"
    label_singular: "Friend" # Used in the UI, ie: "New Post"
    folder: "content/friend"
    create: true
    identifier_field: friend_name
    fields:
      - { label: "Name", name: "friend_name", widget: "string"}
      - label: "Media List"
        widget: "list"
        name: "friend_media_list"
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - label: "Media"
          name: "friend_media"
          widget: "file"
          default: null
          media_library:
            config:
              multiple: true
