backend:
  name: git-gateway
  local_backend: true
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "friends"
    label: "Friends"
    label_singular: "Friend" # Used in the UI, ie: "New Post"
    folder: "content/friend"
    create: true
    fields:
          - { label: "Name", name: "friend_name", widget: "string"}
          - label: "Media"
            name: "friend_media"
            widget: "file"
            config:
              allow_multiple: true
